### PR TITLE
Fix layout config

### LINKED ISSUE #42: Issue with loading template with multiple tabs and sections
Hi there,

I'm running into an issue loading a saved template correctly. The template JSON and a notebook with a minimal example is attached. The template I saved had two "Section" (tabs on the bottom) and Section One has one widget box up top and 3 widgets in "Tabs" on the bottom.

[   ----------   Header   ----------   ]
    [   --------  Widget 1  --------  ]
    [Widget 2 | Widget 3 | Widget 4]

   |**Section One** | Section Two |

When the template is loaded with editable=True, you'll only see Widget 1 up top and Widget 2 on the bottom but if you right click on each of them you can "Show Tab Bar" which makes Widgets 3 and 4 available too. But I don't think there's a way to bring Section Two back into view. Is there a way to make sure sure that all of the widget tabs and sections are visible when reloading using a template? 

Thanks!!

[ipyflex-issue.zip](https://github.com/trungleduc/ipyflex/files/9568165/ipyflex-issue.zip)

### PR DESCRIPTION
**Pull request by trungleduc**
Closes #42

### CODE REVIEW

**Comment by trungleduc** [comment]
Hey @dzhuliya, could you try this fix by using the binder button above? It works well locally but I'm not sure it fixes all your issues.

**Comment by dzhuliya** [comment]
@trungleduc I'm having issues with the Binder link, error says "github recently changed default branches from "master" to "main"". But I was able to test your updates locally in my test environment and it looks like it works! All of the tabs and both sections appear exactly as expected based on the template. thank you so much!

**Comment by trungleduc** [comment]
Great, i will release a new version with this fix.

**Comment by trungleduc** [comment]
@dzhuliya `0.2.4` is out with the patch.

**Pull request merged**
